#!/usr/bin/env bash
# Build the PyInstaller --onedir sidecar for the Tauri Mac app.
#
# After success, the sidecar bundle lives at:
#   app-mac/python-sidecar/build/geospatial-atlas-sidecar/
# and the "externalBin" wrapper expected by Tauri lives at:
#   app-mac/src-tauri/binaries/geospatial-atlas-sidecar-<triple>
#
# The wrapper is a tiny shell stub that execs into the onedir's inner binary
# with all CLI args + env preserved. Tauri's externalBin feature requires a
# single binary named <basename>-<triple>, but PyInstaller --onedir produces
# a directory tree; the stub bridges the two and points at the real binary
# inside the app Resources folder at runtime.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_MAC="$(cd "$HERE/.." && pwd)"
REPO="$(cd "$APP_MAC/.." && pwd)"
BACKEND="$REPO/packages/backend"

# Target triple. Defaults to host. Override with TARGET_TRIPLE=... for x86_64
# cross-build via Rosetta.
TARGET_TRIPLE="${TARGET_TRIPLE:-}"
if [ -z "$TARGET_TRIPLE" ]; then
  case "$(uname -m)" in
    arm64) TARGET_TRIPLE="aarch64-apple-darwin" ;;
    x86_64) TARGET_TRIPLE="x86_64-apple-darwin" ;;
    *) echo "Unsupported arch $(uname -m)" >&2; exit 1 ;;
  esac
fi

echo "[build-sidecar] target triple: $TARGET_TRIPLE"
echo "[build-sidecar] backend:       $BACKEND"

# 1. Make sure viewer static assets are built & present in the backend package.
if [ ! -f "$BACKEND/embedding_atlas/static/index.html" ]; then
  echo "[build-sidecar] viewer static missing — running backend/build.sh"
  (cd "$BACKEND" && ./build.sh)
fi

# 2. Run PyInstaller from the backend venv (ephemeral --with, doesn't touch pyproject.toml).
BUILD_DIR="$HERE/build"
DIST_DIR="$HERE/dist"
rm -rf "$BUILD_DIR" "$DIST_DIR"
mkdir -p "$BUILD_DIR" "$DIST_DIR"

echo "[build-sidecar] running pyinstaller…"
(
  cd "$HERE"
  uv run \
    --project "$BACKEND" \
    --with "pyinstaller>=6.10" \
    pyinstaller sidecar.spec \
      --noconfirm \
      --distpath "$DIST_DIR" \
      --workpath "$BUILD_DIR"
)

ONEDIR="$DIST_DIR/geospatial-atlas-sidecar"
INNER_BIN="$ONEDIR/geospatial-atlas-sidecar"

if [ ! -x "$INNER_BIN" ]; then
  echo "[build-sidecar] ERROR: expected binary at $INNER_BIN" >&2
  exit 1
fi

# 4. Copy the onedir into resources/ so Tauri bundles it under Contents/Resources/.
RESOURCES="$APP_MAC/resources"
rm -rf "$RESOURCES/sidecar"
mkdir -p "$RESOURCES/sidecar"
cp -R "$ONEDIR/." "$RESOURCES/sidecar/"

# 5. Write the externalBin stub that Tauri expects.
#    It lives at src-tauri/binaries/geospatial-atlas-sidecar-<triple>
#    and at runtime execs into the onedir bundled under Resources/.
BIN_DIR="$APP_MAC/src-tauri/binaries"
mkdir -p "$BIN_DIR"
STUB="$BIN_DIR/geospatial-atlas-sidecar-$TARGET_TRIPLE"

cat > "$STUB" <<'STUB_EOF'
#!/usr/bin/env bash
# Auto-generated by app-mac/python-sidecar/build.sh.
# Forwards all args/env to the real PyInstaller --onedir binary bundled
# under Contents/Resources/sidecar/.
set -e
SELF="${BASH_SOURCE[0]}"
while [ -L "$SELF" ]; do SELF="$(readlink "$SELF")"; done
DIR="$(cd "$(dirname "$SELF")" && pwd)"

# Candidate 1: packaged inside a .app -> Contents/Resources/sidecar/
CAND1="$(cd "$DIR/.." && pwd)/Resources/sidecar/geospatial-atlas-sidecar"
# Candidate 2: running from src-tauri/binaries during `tauri dev`
CAND2="$DIR/../../resources/sidecar/geospatial-atlas-sidecar"
# Candidate 3: same dir (if stub is replaced by real binary)
CAND3="$DIR/geospatial-atlas-sidecar"

for C in "$CAND1" "$CAND2" "$CAND3"; do
  if [ -x "$C" ]; then
    exec "$C" "$@"
  fi
done

echo "geospatial-atlas-sidecar: could not locate bundled binary" >&2
echo "  tried: $CAND1" >&2
echo "  tried: $CAND2" >&2
echo "  tried: $CAND3" >&2
exit 127
STUB_EOF
chmod +x "$STUB"

echo "[build-sidecar] OK"
echo "  onedir: $ONEDIR"
echo "  bundled into: $RESOURCES/sidecar"
echo "  stub: $STUB"
